"""Atlas add-source developer scaffold (Phase 1A, dry-run first).

Generates the *templates* a new source adapter needs (adapter module,
descriptor, contract test, fixture, docs) so a future contributor gets a
consistent starting point. This is a developer tool, not a runtime feature:
by default it only prints a plan (``--dry-run``) and writes nothing. It
deliberately does NOT generate any real adapter (Greenhouse/Lever/Workday/
LinkedIn/Naukri) in Phase 1A — only a neutral template.
"""

from __future__ import annotations

import keyword
import re
from pathlib import Path
from typing import Optional

from atlas.sources.models import (
    SourceCategory,
    SourceType,
    category_for_family,
    family_for_source_type,
)

_REAL_FAMILY_HINTS = {
    "greenhouse", "lever", "workday", "linkedin", "naukri", "foundit",
    "indeed", "wellfound", "instahyre", "smartrecruiters",
}


def _class_name(name: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", name)
    camel = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if not camel or not camel[0].isalpha():
        camel = "Source" + camel
    return camel + "Adapter"


def _module_name(name: str) -> str:
    mod = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").lower()
    if not mod or mod[0].isdigit() or keyword.iskeyword(mod):
        mod = "source_" + mod
    return mod


def validate_scaffold_request(name: str, source_type: str) -> SourceType:
    if not name or not name.strip():
        raise ValueError("source name must not be empty")
    try:
        st = SourceType(source_type)
    except ValueError as exc:
        raise ValueError(
            f"unknown source_type {source_type!r}; valid: {[t.value for t in SourceType]}"
        ) from exc
    return st


def generate_scaffold(name: str, source_type: str, base_url: Optional[str] = None) -> dict[str, str]:
    """Return a mapping of relative-path → file content for a new adapter.
    Pure function: writes nothing. Derives the SourceFamily (adapter key) and
    SourceCategory from the type, routes ATS families to ``atlas/sources/ats/``
    and portal families to ``atlas/sources/portals/``, seeds NO guessed
    capabilities beyond SEARCH, and includes the exact typed result contract
    plus contract/health tests and a parser fixture (build spec 23)."""
    st = validate_scaffold_request(name, source_type)
    family = family_for_source_type(st)
    category = category_for_family(family)
    cls = _class_name(name)
    mod = _module_name(name)

    is_ats = category == SourceCategory.ATS
    adapter_dir = "atlas/sources/ats" if is_ats else (
        "atlas/sources/portals" if category == SourceCategory.PORTAL else "atlas/sources"
    )
    # DISCOVER (enumerate entry points) applies to ATS/company-careers families.
    discover_applicable = category in (SourceCategory.ATS,) or st == SourceType.COMPANY_CAREER
    cap_lines = "Capability.SEARCH, Capability.DETAIL"
    if discover_applicable:
        cap_lines += ", Capability.DISCOVER"

    adapter_py = f'''"""{cls}: TEMPLATE generated by `atlas add-source` — implement before use.

Family (adapter_key): {family.value}   Category: {category.value}
Register with @register_source once implemented and contract-tested.
"""

from __future__ import annotations

from atlas.sources.adapter import SourceAdapter, AdapterError, new_result_base
from atlas.sources.health import SourceHealth, SourceHealthState
from atlas.sources.models import (
    Capability, DetailRequest, DiscoveryResult, SearchRequest, SearchResult,
    SourceFamily, SourceInstance, SourceType,
)


class {cls}(SourceAdapter):
    source_type = SourceType.{st.name}
    source_family = SourceFamily.{family.name}          # explicit registry identity
    # NO guessed capabilities — declare ONLY what the source actually supports.
    CAPABILITIES = frozenset({{{cap_lines}}})
    adapter_version = "0.1.0"
    parser_version = "0.1.0"

    def health_check(self) -> SourceHealth:
        raise NotImplementedError("implement a read-only reachability probe (no search)")
'''
    if discover_applicable:
        adapter_py += '''
    def discover(self, request):
        # Enumerate entry points (careers/board/tenant) — a DISTINCT capability
        # from SEARCH. Only implement if the source truly enumerates.
        raise NotImplementedError
'''
    adapter_py += '''
    def search(self, request: SearchRequest) -> SearchResult:
        # Exact typed contract: return a SearchResult of DiscoveryResult objects
        # (one attempt per call, NO retries/sleeps here). Parse each raw item
        # independently via atlas.sources.parsing.parse_isolated; seed provenance
        # with new_result_base(self, ...). Classify a zero via ZeroResultKind and
        # raise AdapterError(category, ...) on a classified failure.
        raise NotImplementedError

    def fetch_detail(self, request: DetailRequest) -> DiscoveryResult:
        raise NotImplementedError
'''

    destination = "ats" if is_ats else ("portals" if category == SourceCategory.PORTAL else "custom")
    descriptor_yaml = f'''# Descriptor template for the {name!r} source.
# adapter_key (family): {family.value}   category: {category.value}   destination: {destination}
instances:
  - instance_id: {mod}-example
    source_type: {st.value}
    source_family: {family.value}
    display_name: {name} (example)
    base_url: {base_url or "https://example.invalid"}
    enabled: false          # keep disabled until implemented + tested
    # auth_ref: {mod.upper()}_API_TOKEN   # a REFERENCE only, never a secret value
    # url_reference: document the exact search/detail endpoints + access notes
    #   (public/API/browser, robots posture, rate limits) — no bypass of controls.
    rate_policy:
      min_interval_seconds: 1.0
      max_concurrency: 1
'''

    test_py = f'''"""Contract + health tests for {cls} (fill in a factory returning scripted adapters)."""

import pytest
from atlas.sources.testing.contract import run_contract_checks

pytestmark = pytest.mark.unit


def _factory(scenario):
    # Return a {cls} configured for `scenario`, or None to SKIP that check.
    return None  # TODO: implement using fixtures under tests/fixtures/sources/{mod}/


def test_{mod}_contract():
    report = run_contract_checks(_factory)
    assert report.ok, report.render()


def test_{mod}_health_check():
    adapter = _factory("results")
    if adapter is None:
        pytest.skip("implement _factory to enable the health test")
    health = adapter.health_check()
    assert health is not None
'''

    fixture_json = '''{
  "items": [
    {"id": "1", "title": "Example Role", "company": "Example Co",
     "location": "Bengaluru, India", "status": "open", "work_mode": "remote"}
  ]
}
'''

    doc_md = f'''# {name} source adapter

- **source_type**: `{st.value}`
- **adapter_key (family)**: `{family.value}`
- **category**: `{category.value}`
- **base_url**: `{base_url or "TBD"}`
- **DISCOVER capability**: {"applicable" if discover_applicable else "not applicable"}
- **status**: TEMPLATE — not implemented.

## URL reference / access notes

Document the exact search + detail endpoints, the access mechanism
(public/API/browser), robots/ToS posture, and observed rate limits. Never
bypass any access control. Credentials come from an `auth_ref` env var only.

Implement `search`/`fetch_detail`/`health_check` (+ `discover` when applicable),
add sanitized fixtures, and make the contract + health tests pass before
enabling the instance.
'''

    return {
        f"{adapter_dir}/{mod}.py": adapter_py,
        f"config/sources/{mod}.yaml": descriptor_yaml,
        f"tests/test_source_{mod}.py": test_py,
        f"tests/fixtures/sources/{mod}/search.json": fixture_json,
        f"docs/sources/{mod}.md": doc_md,
    }


def render_plan(name: str, source_type: str, base_url: Optional[str] = None) -> str:
    files = generate_scaffold(name, source_type, base_url)
    warn = ""
    if _module_name(name) in _REAL_FAMILY_HINTS or name.lower() in _REAL_FAMILY_HINTS:
        warn = (
            "\nNOTE: Phase 1A does not ship real adapters. This is a TEMPLATE only; "
            "implement and test before enabling.\n"
        )
    lines = [f"add-source DRY-RUN plan for {name!r} (type={source_type}):", ""]
    for path, content in files.items():
        lines.append(f"  would create: {path}  ({len(content)} bytes)")
    lines.append(warn)
    return "\n".join(lines)


def write_scaffold(name: str, source_type: str, out_dir: Path, base_url: Optional[str] = None) -> list[Path]:
    """Write the template files under ``out_dir`` (a disposable/explicit dir).
    Never overwrites existing files."""
    files = generate_scaffold(name, source_type, base_url)
    written: list[Path] = []
    for rel, content in files.items():
        target = out_dir / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists():
            raise FileExistsError(f"refusing to overwrite {target}")
        target.write_text(content, encoding="utf-8")
        written.append(target)
    return written


__all__ = ["generate_scaffold", "render_plan", "write_scaffold", "validate_scaffold_request"]
